### ISSUE TITLE
Forbidden StatusCode: 403

### ISSUE THREAD

**Issue by Andrey-Pavlov** [k3rn31p4nic/google-translate-api#5] opened 2019-07-10 15:50 UTC
```
 https://translate.google.com/translate_a/single?client=gtx&sl=en&tl=ru&hl=ru&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=menka&tk=86352.86352
```
```
info: Microsoft.AspNetCore.NodeServices[0]
      { HTTPError
          at translate (C:\Projects\service\node_modules\@k3rn31p4nic\google-translate-api\src\index.js:145:19)
          at process._tickCallback (internal/process/next_tick.js:68:7)
        name: 'HTTPError',
        statusCode: 403,
        statusMessage: 'Forbidden' }
```

**Comment by k3rn31p4nic** [comment] 2019-07-10 22:37
Can you give some details?

**Comment by Andrey-Pavlov** [comment] 2019-07-11 14:52
It happens randomly 30%-50% of tries.
![Fiddler_ovRlq1DH9Q](https://user-images.githubusercontent.com/7976740/61061226-8635ad80-a404-11e9-9a4b-245702055590.png)

**Comment by k3rn31p4nic** [comment] 2019-07-11 15:24
Why are you directly making the HTTP request instead of using the library?

**Comment by Andrey-Pavlov** [comment] 2019-07-11 15:38
> Why are you directly making the HTTP request instead of using the library?

To provide details for the issue

**Comment by codenaz** [comment] 2019-07-14 11:27
@k3rn31p4nic This happens even when I use the library. The error is not consistent. It returns 403 and when you keep retrying, it then works

**Comment by k3rn31p4nic** [comment] 2019-07-14 16:12
Can you say what you're translating and the source and target language? I'm not able to reproduce this issue.

**Comment by codenaz** [comment] 2019-07-14 16:20
```translate('Bot fix time',{to:'yo'});```
```translate('Bot fix time',{from:'en' to:'es'});```
```translate('Bot fix time',{to:'spanish'});```

That is just one example out of multiple. Every request I try regardless of the query or language gives that error. After retrying about once to four times, it works and then repeats again.

**Comment by k3rn31p4nic** [comment] 2019-07-14 16:33
Okay, I'm getting the same error now. From what I can observer, you'll get this error if you continuously make the request without enough delay (I need confirmation from others too).
If that's the case, I suppose this is a rate limit enforced by Google in their online [translate service](https://translate.google.com) to prevent users like us from using it for purposes like this, for free, instead of using their actual Translate API.

**Comment by codenaz** [comment] 2019-07-14 16:40
Funny enough it happens even on first tries. Unless by delay you mean it tracks request coming from this library?

**Comment by k3rn31p4nic** [comment] 2019-07-14 16:46
No, I meant from the same IP.

**Comment by codenaz** [comment] 2019-07-14 16:49
Then, I doubt it is a delay issue. You can give it some more tries to confirm.

**Comment by k3rn31p4nic** [comment] 2019-07-14 17:28
Probably have to update the token generator.

**Comment by codenaz** [comment] 2019-07-14 17:40
I have a similar feeling.

**Comment by Andrey-Pavlov** [comment] 2019-07-14 20:20
It doesn't depend on delay. Even first try can return 403. Potentially a token generator issue.

**Comment by cxmplex** [comment] 2019-07-17 17:53
Any update on this @k3rn31p4nic ?

**Comment by ZuBB** [comment] 2019-07-17 19:17
How about making request through proxy?

**Comment by Adizbek** [comment] 2019-07-20 16:08
@Andrey-Pavlov I don't think so, it isn't related to token, everything works on localhost, seems google is blocking IP which makes a lot of request.

Yes, adding proxy support would be great.

**Comment by Adizbek** [comment] 2019-07-20 17:22
#8 Check this PR, I didn't found any working proxies yet. But it should work

**Comment by k3rn31p4nic** [comment] 2019-07-22 05:14
Should be fixed by #8

**Closed by k3rn31p4nic** 2019-07-22 05:14 UTC
Labels: not enough information

**Comment by Adizbek** [comment] 2019-07-22 08:04
@k3rn31p4nic Seems google changed API, they are migrating to new API. I think after migration we can't use at all.

**Comment by Adizbek** [comment] 2019-07-22 09:22
Checkout this https://github.com/k3rn31p4nic/google-translate-api/pull/8#issuecomment-513711276, should work
